//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTrack {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringContainer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringContainer() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MediTrack.StringContainer", typeof(StringContainer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MQTTHandler: Initialised ähnelt.
        /// </summary>
        internal static string HandlerIntializer {
            get {
                return ResourceManager.GetString("HandlerIntializer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MQTTQueue: Entry Read In ähnelt.
        /// </summary>
        internal static string MonitorIDFound {
            get {
                return ResourceManager.GetString("MonitorIDFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MQTTHandler: Subscription Was Successful ähnelt.
        /// </summary>
        internal static string MQTTSubScribeSucc {
            get {
                return ResourceManager.GetString("MQTTSubScribeSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MQTTHandler: SubScribed To Topic ähnelt.
        /// </summary>
        internal static string MQTTSubScribeTopic {
            get {
                return ResourceManager.GetString("MQTTSubScribeTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PatientDictionary: Patient Found ähnelt.
        /// </summary>
        internal static string PatientDictPatFound {
            get {
                return ResourceManager.GetString("PatientDictPatFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PatientDictionary: Patient Not Found ähnelt.
        /// </summary>
        internal static string PatientDictPatNotFound {
            get {
                return ResourceManager.GetString("PatientDictPatNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PatientDictionary: Removed PatiendID Failed ähnelt.
        /// </summary>
        internal static string PatientDictRemovedFai {
            get {
                return ResourceManager.GetString("PatientDictRemovedFai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PatientDictionary: Removed PatiendID Successful For  ähnelt.
        /// </summary>
        internal static string PatientDictRemovedSuc {
            get {
                return ResourceManager.GetString("PatientDictRemovedSuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PatientDictionary: Searched Patient Found ähnelt.
        /// </summary>
        internal static string PatientDictSearchedFound {
            get {
                return ResourceManager.GetString("PatientDictSearchedFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PatientDictionary: Searched Patient Not Found ähnelt.
        /// </summary>
        internal static string PatientDictSearchedFoundNot {
            get {
                return ResourceManager.GetString("PatientDictSearchedFoundNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die UUIDDictionary: Dictionary Does Not Contain UUID ähnelt.
        /// </summary>
        internal static string UUIDDictionaryContainFai {
            get {
                return ResourceManager.GetString("UUIDDictionaryContainFai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die UUIDDictionary: Dictionary Does Contain UUID ähnelt.
        /// </summary>
        internal static string UUIDDictionaryContainSuc {
            get {
                return ResourceManager.GetString("UUIDDictionaryContainSuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die UUIDDictionary: MonitorID Isnt Bound At All ähnelt.
        /// </summary>
        internal static string UUIDDictionaryFai {
            get {
                return ResourceManager.GetString("UUIDDictionaryFai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die UUIDDictionary: Inserted UUID Unsuccessful For ähnelt.
        /// </summary>
        internal static string UUIDDictionaryInsertFai {
            get {
                return ResourceManager.GetString("UUIDDictionaryInsertFai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die UUIDDictionary: Inserted UUID Successful For ähnelt.
        /// </summary>
        internal static string UUIDDictionaryInsertSuc {
            get {
                return ResourceManager.GetString("UUIDDictionaryInsertSuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die UUIDDictionary: Removed UUID Unseccessful ähnelt.
        /// </summary>
        internal static string UUIDDictionaryRemovedFai {
            get {
                return ResourceManager.GetString("UUIDDictionaryRemovedFai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die UUIDDictionary: Removed UUID Successful For  ähnelt.
        /// </summary>
        internal static string UUIDDictionaryRemovedSuc {
            get {
                return ResourceManager.GetString("UUIDDictionaryRemovedSuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die UUIDDictionary: MonitorID Is Bound To UUID ähnelt.
        /// </summary>
        internal static string UUIDDictionarySuc {
            get {
                return ResourceManager.GetString("UUIDDictionarySuc", resourceCulture);
            }
        }
    }
}
